import Link from 'next/link'
import { ArrowRight, BrainCircuit, Code2, HeartPulse, ShieldCheck, Sprout, Sparkles } from 'lucide-react'

const data: Record<string, { eyebrow: string; title: string; copy: string; items: { title: string; copy: string }[] }> = {
  about: { eyebrow: 'WHY HACKFEST?', title: 'Build what matters.', copy: 'HackFest 2026 is a two-day collaborative hackathon where students, developers, designers and innovators turn meaningful ideas into working technology.', items: [{ title: 'Our mission', copy: 'Make ambitious building accessible, practical, and human.' }, { title: 'What you will experience', copy: 'Fast collaboration, real feedback, focused making, and a stage for your work.' }, { title: 'Who can participate', copy: 'Students, professionals, first-time hackers, designers, and curious problem-solvers.' }] },
  tracks: { eyebrow: 'SIX DIRECTIONS', title: 'Choose your challenge.', copy: 'Pick a problem space, bring your perspective, and build something useful.', items: ['AI & Machine Learning', 'Web & App Development', 'Cybersecurity', 'HealthTech', 'Sustainability', 'Open Innovation'].map((title) => ({ title, copy: 'Explore ideas, tools, and technologies that can move this track forward.' })) },
  schedule: { eyebrow: '13–14 SEPT 2026', title: 'A weekend worth remembering.', copy: 'Two focused days from opening ceremony to final demo.', items: [{ title: 'Day 01 — Build', copy: 'Registration, challenge reveal, hacking begins, mentor connect, progress check.' }, { title: 'Day 02 — Ship', copy: 'Final sprint, submission deadline, project demos, judging, and closing ceremony.' }] },
  mentors: { eyebrow: 'THE PEOPLE WHO PUSH YOU FURTHER', title: 'Meet your next perspective.', copy: 'Get guidance from people who have built, launched, and solved problems in the real world.', items: ['Aarav Mehta — Product Engineering Lead', 'Riya Sharma — Founder & Technology Strategist', 'Kabir Sen — Senior Software Engineer', 'Ananya Rao — Cybersecurity Specialist'].map((title) => ({ title, copy: 'Demo profile · AI, product, engineering, and digital trust.' })) },
  prizes: { eyebrow: 'DEMO PRIZES', title: 'Build big. Win big.', copy: 'Recognition for thoughtful products, strong craft, and meaningful impact.', items: [{ title: 'Grand Prize · ₹50,000', copy: 'For the strongest overall submission.' }, { title: 'Runner Up · ₹25,000', copy: 'For an exceptional idea and execution.' }, { title: 'Special awards', copy: 'Best UI/UX, Best AI Solution, Best Social Impact, Best Beginner Team.' }] },
  faq: { eyebrow: 'QUESTIONS, ANSWERED', title: 'Everything you need to know.', copy: 'Registration is free, teams are 2–4 people, and beginners are welcome.', items: ['Who can participate?', 'What technologies can I use?', 'How will projects be judged?', 'Can I participate without a team?'].map((title) => ({ title, copy: 'Yes. Bring your curiosity and we will help you find your way into the build.' })) },
  contact: { eyebrow: 'LET’S TALK', title: 'Bring us your questions.', copy: 'hello@hackfest-demo.dev · Information Technology department, Gauhati University', items: [{ title: 'Email the team', copy: 'hello@hackfest-demo.dev' }, { title: 'Find the venue', copy: 'Information Technology department, Gauhati University · Hybrid event' }] },
}

export function Subpage({ kind }: { kind: keyof typeof data }) {
  const page = data[kind]
  return <main className="subpage"><header className="subnav"><Link href="/" className="logo">HACKFEST <small>26</small></Link><nav><Link href="/about">About</Link><Link href="/tracks">Tracks</Link><Link href="/schedule">Schedule</Link><Link href="/mentors">Mentors</Link><Link href="/prizes">Prizes</Link><Link className="button" href="/register">Register Now <ArrowRight size={16} /></Link></nav></header><section className="subpage-hero"><span className="eyebrow">{page.eyebrow}</span><h1>{page.title}</h1><p>{page.copy}</p></section><section className="subpage-grid">{page.items.map((item, index) => <article key={item.title}><span className="subpage-index">0{index + 1}</span><h2>{item.title}</h2><p>{item.copy}</p><ArrowRight size={18} /></article>)}</section><footer className="subfooter"><span>© 2026 HackFest. Demo project created for educational purposes.</span><Link href="/">Back to home</Link></footer></main>
}
